CREATE VIEW [edw].[V_test_MpcTripSummary]
AS
SELECT
       [edw].[MPC_MpcTripSummary].[MpcTripId]
      ,[edw].[MPC_MpcTripSummary].[TripId]
      ,[edw].[MPC_MpcTripSummary].[TripStatus]
      ,[edw].[MPC_MpcTripSummary].[TripLastModified]
      ,[edw].[MPC_MpcTripSummary].[StopName]
      ,[edw].[MPC_MpcTripSummary].[PassengersIn]
      ,[edw].[MPC_MpcTripSummary].[PassengersOut]
      ,[edw].[MPC_MpcTripSummary].[CarsIn]
      ,[edw].[MPC_MpcTripSummary].[CarsOut]
      ,[edw].[MPC_MpcTripSummary].[Cars7mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars7mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars8mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars8mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars10mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars10mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars12mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars12mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars14mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars14mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars17mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars17mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars19mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars19mOut]
      ,[edw].[MPC_MpcTripSummary].[Cars22mIn]
      ,[edw].[MPC_MpcTripSummary].[Cars22mOut]
      ,[edw].[MPC_MpcTripSummary].[MotorcyclesIn]
      ,[edw].[MPC_MpcTripSummary].[MotorcyclesOut]
      ,[edw].[MPC_MpcTripSummary].[CarsLeftBehind]
      ,[edw].[MPC_MpcTripSummary].[QuayRef]
      ,[edw].[MPC_MpcTripSummary].[PublicCode]
      ,[edw].[MPC_MpcTripSummary].[PassingTime]
      ,[edw].[MPC_MpcTripSummary].[TransportType]
      ,[edw].[MPC_MpcTripSummary].[Latitude]
      ,[edw].[MPC_MpcTripSummary].[Longitude]
      ,[edw].[MPC_MpcTripSummary].[CompanyNumber]
      ,[edw].[MPC_MpcTripSummary].[DeviceId]
      ,[edw].[MPC_MpcTripSummary].[LastEventTimestamp]
      ,[arc].[TTDB_LINES].[PublicCode] AS Route_short_name
      ,[arc].[TTDB_Quays].[KolumbusId]
  FROM [edw].[MPC_MpcTripSummary]
LEFT JOIN [arc].[TTDB_Lines] ON LEFT([edw].[MPC_MpcTripSummary].TripId, 4) = [arc].[TTDB_Lines].[PrivateCode]
LEFT JOIN [arc].[TTDB_Quays] ON [edw].[MPC_MpcTripSummary].[QuayRef] = arc.[TTDB_Quays].[QuayRef]

