using System.Text;
using SqlFlow.Core.Abstractions;
using SqlFlow.Core.Model;

namespace SqlFlow.Sources;

/// <summary>
/// Renders a discovered source's flatten formula as a runnable flow document: the source with its resolved flatten
/// options, a string-typed target, per-column provenance in comments, and the collision mappings that keep the
/// projection lossless. The <c>flatten</c> CLI verb and the control-plane source-discover endpoint both emit through
/// here so the generated YAML is identical whichever entry point produced it.
/// </summary>
public static class FlattenFlowYaml
{
    /// <summary>SQLFlow's own landing default (see <see cref="Core.Model.SchemaPolicy.DefaultColumnType"/>): a lean,
    /// single-byte type. nvarchar is only worth its doubled storage when the data is known to exceed Latin-1.</summary>
    public const string DefaultColumnType = "varchar(255)";

    /// <summary>Builds the flatten-formula flow YAML for a scanned source and its introspection. The generated
    /// <c>schema.defaultColumnType</c> is <paramref name="defaultColumnType"/> (defaults to <see cref="DefaultColumnType"/>);
    /// large-text columns are widened to that type's MAX variant so they never overflow the scalar default.</summary>
    public static string Build(SourceSpec source, FlattenIntrospection introspection, string? defaultColumnType = null)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(introspection);
        var columnType = string.IsNullOrWhiteSpace(defaultColumnType) ? DefaultColumnType : defaultColumnType.Trim();

        var formula = introspection.Formula;
        var inventory = introspection.Inventory;
        var name = SanitizeFlowName(Path.GetFileNameWithoutExtension(source.Location ?? "flow"));
        var userMappings = introspection.Options.FirstOrDefault(o => o.Key == "columnMappings").Value;
        var mappings = MergeMappings(userMappings, formula.CollisionMappings);

        var sb = new StringBuilder();
        sb.Append("# Flatten formula for ").Append(Path.GetFileName(source.Location ?? "?"))
          .Append(" - ").Append(formula.Columns.Count).Append(" column(s), ")
          .Append(inventory.RecordsScanned).Append(" record(s), ")
          .Append(inventory.FilesScanned).AppendLine(" file(s).");
        sb.AppendLine("# Generated by 'sqlflow flatten'. Set target.connection, then 'sqlflow run' this file.");
        if (introspection.AutoDetectedGrain is { } grain)
        {
            var label = introspection.SourceType == "xml" ? "rowXPath" : "rootPath";
            sb.Append("# Record grain auto-detected from sample statistics (").Append(label).Append(": ")
              .Append(grain).AppendLine("); one row per record.");
        }

        sb.Append("name: ").AppendLine(name);
        sb.AppendLine("source:");
        sb.Append("  type: ").AppendLine(introspection.SourceType);
        sb.Append("  location: ").AppendLine(source.Location);
        sb.AppendLine("  options:");
        foreach (var (key, value) in introspection.Options)
        {
            if (key != "columnMappings")
            {
                AppendOptionLine(sb, key, value);
            }
        }

        AppendOptionLine(sb, "columnMappings", mappings.Length == 0 ? null : mappings);
        sb.AppendLine("target:");
        sb.AppendLine("  connection: ${env:SQLFlowSinkConStr}");
        sb.AppendLine("  schema: dbo");
        sb.Append("  table: ").AppendLine(name);
        sb.AppendLine("schema:");
        sb.Append("  defaultColumnType: ").AppendLine(columnType);

        // Columns that hold whole-array / kept-subtree text can be arbitrarily large, so type them as the MAX
        // variant of the chosen family rather than letting them overflow the scalar default.
        var maxType = MaxVariant(columnType);
        var largeTextColumns = formula.Columns.Where(c => c.IsLargeText).ToList();
        if (largeTextColumns.Count > 0)
        {
            sb.AppendLine("  overrides:");
            foreach (var column in largeTextColumns)
            {
                sb.Append("    ").Append(column.Name).AppendLine(":");
                sb.Append("      type: ").AppendLine(maxType);
            }
        }

        sb.AppendLine("load:");
        sb.AppendLine("  mode: truncate-load");
        sb.AppendLine("# columns (column <- source path):");
        foreach (var column in formula.Columns)
        {
            sb.Append("#   ").Append(column.Name.PadRight(34)).Append(" <- ").AppendLine(column.SourcePath);
        }

        if (formula.CollisionMappings.Count > 0)
        {
            sb.Append("# ").Append(formula.CollisionMappings.Count)
              .AppendLine(" name collision(s) auto-resolved via columnMappings above (kept lossless).");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Renders a straight columnar ingestion flow for a tabular source (CSV, Excel, Parquet): the source with its
    /// resolved scan options, the discovered columns typed by the target type mapper, and a truncate-load into a
    /// string-first table. There is no flatten section because tabular data has no nested structure to flatten.
    /// </summary>
    public static string BuildColumnar(
        SourceSpec source, string sourceType, IReadOnlyList<SourceColumn> columns, ISqlTypeMapper typeMapper,
        int filesScanned, string? defaultColumnType = null)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(columns);
        ArgumentNullException.ThrowIfNull(typeMapper);

        var defaultType = string.IsNullOrWhiteSpace(defaultColumnType) ? DefaultColumnType : defaultColumnType.Trim();
        var name = SanitizeFlowName(Path.GetFileNameWithoutExtension(source.Location ?? "flow"));

        var sb = new StringBuilder();
        sb.Append("# Ingestion flow for ").Append(Path.GetFileName(source.Location ?? "?"))
          .Append(" - ").Append(columns.Count).Append(" column(s), schema sampled from ")
          .Append(filesScanned).AppendLine(" file(s).");
        sb.AppendLine("# Generated by SQLFlow discover. Set target.connection, then 'sqlflow run' this file.");

        sb.Append("name: ").AppendLine(name);
        sb.AppendLine("source:");
        sb.Append("  type: ").AppendLine(sourceType);
        sb.Append("  location: ").AppendLine(source.Location);
        sb.AppendLine("  options:");
        foreach (var (key, value) in source.Options)
        {
            AppendOptionLine(sb, key, value);
        }

        sb.AppendLine("target:");
        sb.AppendLine("  connection: ${env:SQLFlowSinkConStr}");
        sb.AppendLine("  schema: dbo");
        sb.Append("  table: ").AppendLine(name);
        sb.AppendLine("schema:");
        sb.Append("  defaultColumnType: ").AppendLine(defaultType);

        // Only self-describing formats (Parquet) carry real types; emit an override for each column whose target
        // type differs from the string default, so a CSV/Excel source stays string-first and Parquet keeps its types.
        var overrides = columns
            .Select(c => (c.Name, Sql: typeMapper.Map(c, null, defaultType).SqlType))
            .Where(c => !string.Equals(c.Sql, defaultType, StringComparison.OrdinalIgnoreCase))
            .ToList();
        if (overrides.Count > 0)
        {
            sb.AppendLine("  overrides:");
            foreach (var (column, sql) in overrides)
            {
                sb.Append("    ").Append(column).AppendLine(":");
                sb.Append("      type: ").AppendLine(sql);
            }
        }

        sb.AppendLine("load:");
        sb.AppendLine("  mode: truncate-load");
        sb.AppendLine("# columns (column : target type):");
        foreach (var column in columns)
        {
            sb.Append("#   ").Append(column.Name.PadRight(34)).Append(" : ")
              .AppendLine(typeMapper.Map(column, null, defaultType).SqlType);
        }

        return sb.ToString();
    }

    /// <summary>The MAX-length variant of a column type's family: nvarchar(...) -> nvarchar(max), else varchar(max).</summary>
    public static string MaxVariant(string columnType)
        => columnType.TrimStart().StartsWith("nvarchar", StringComparison.OrdinalIgnoreCase) ? "nvarchar(max)" : "varchar(max)";

    private static void AppendOptionLine(StringBuilder sb, string key, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            sb.Append("    ").Append(key).Append(": \"").Append(value).AppendLine("\"");
        }
    }

    private static string MergeMappings(string? existing, IReadOnlyDictionary<string, string> collisions)
    {
        var parts = new List<string>();
        if (!string.IsNullOrWhiteSpace(existing))
        {
            parts.Add(existing.Trim().TrimEnd(';').Trim());
        }

        foreach (var (path, column) in collisions)
        {
            parts.Add($"{path}={column}");
        }

        return string.Join("; ", parts);
    }

    private static string SanitizeFlowName(string raw)
    {
        var chars = raw.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        var cleaned = new string(chars).Trim('_');
        if (cleaned.Length == 0 || char.IsAsciiDigit(cleaned[0]))
        {
            cleaned = "_" + cleaned;
        }

        return cleaned;
    }
}
