// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlFlow.Delivery.Data;

#nullable disable

namespace SqlFlow.Delivery.Data.Migrations
{
    [DbContext(typeof(OsduDbContext))]
    [Migration("20260929012241_AssertionRuns")]
    partial class AssertionRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryActivity", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeliveryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("PartitionId", "ActivityId");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("PartitionId", "StartedUtc");

                    b.HasIndex("PartitionId", "Actor", "StartedUtc");

                    b.HasIndex("PartitionId", "FlowId", "StartedUtc");

                    b.HasIndex("PartitionId", "Kind", "StartedUtc");

                    b.HasIndex("PartitionId", "FlowId", "DeliveryKey", "StartedUtc");

                    b.ToTable("Activity", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryAssertionResult", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResultId"));

                    b.Property<long>("AssertionRunId")
                        .HasColumnType("bigint");

                    b.Property<int>("Assertions")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("Evaluated")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedAssertions")
                        .HasColumnType("int");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long?>("Matched")
                        .HasColumnType("bigint");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Sampled")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PartitionId", "ResultId");

                    b.HasIndex("ResultId")
                        .IsUnique();

                    b.HasIndex("PartitionId", "AssertionRunId");

                    b.HasIndex("PartitionId", "FlowId", "TestName", "AssertionRunId");

                    b.ToTable("AssertionResult", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryAssertionRun", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("AssertionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssertionRunId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionsHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Errored")
                        .HasColumnType("int");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Passed")
                        .HasColumnType("int");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Selection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skipped")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Tests")
                        .HasColumnType("int");

                    b.Property<int>("Warned")
                        .HasColumnType("int");

                    b.HasKey("PartitionId", "AssertionRunId");

                    b.HasIndex("AssertionRunId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("PartitionId", "FlowId", "StartedUtc");

                    b.ToTable("AssertionRun", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryAttempt", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptId"));

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeliveryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SourceDeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<long?>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SourceUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("TargetVersion")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkBatch")
                        .HasColumnType("int");

                    b.Property<string>("Worker")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PartitionId", "AttemptId");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("SubmissionId", "Outcome", "Phase");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SubmissionId", "Outcome", "Phase"), new[] { "DeliveryKey" });

                    b.HasIndex("PartitionId", "FlowId", "DeliveryKey", "StartedUtc");

                    b.HasIndex("RunId", "PartitionId", "FlowId", "DeliveryKey");

                    b.ToTable("Attempt", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Connection")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("DeclaresPartitions")
                        .HasColumnType("bit");

                    b.Property<string>("DictionaryPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeyField")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Kind")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OnChange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("osdu");

                    b.Property<string>("Query")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceObject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("FlowName");

                    b.HasIndex("Scope", "Name");

                    b.HasIndex("RepoId", "FlowName", "Name", "Scope")
                        .IsUnique();

                    b.ToTable("CacheDefinition", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemId"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromSequence")
                        .HasColumnType("int");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToSequence")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ItemId"), false);

                    b.HasIndex("Scope", "ItemId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Scope", "ItemId"));

                    b.HasIndex("Scope", "ToSequence");

                    b.HasIndex("Scope", "TypeName", "RecordId", "FromSequence")
                        .IsUnique();

                    b.ToTable("CacheItem", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheMember", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("FlowName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Scope", "TypeName", "RecordId", "FlowName");

                    b.HasIndex("Scope", "FlowName", "TypeName");

                    b.ToTable("CacheMember", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheSet", b =>
                {
                    b.Property<long>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SetId"));

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SetHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("SetId");

                    b.HasIndex("Gated")
                        .HasFilter("[Gated] = 1");

                    b.HasIndex("SetHash")
                        .IsUnique();

                    b.ToTable("CacheSet", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheSetEntry", b =>
                {
                    b.Property<long>("SetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ItemId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Path")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ValueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("SetId", "Scope", "TypeName", "ItemId", "Path", "Kind");

                    b.HasIndex("Scope", "TypeName", "ItemId");

                    b.ToTable("CacheSetEntry", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryCacheVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Items")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SystemPropertiesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("TypesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("RunId");

                    b.HasIndex("Scope", "Sequence")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Scope", "Sequence"));

                    b.HasIndex("Scope", "Version")
                        .IsUnique();

                    b.ToTable("CacheVersion", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryConfigProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Partition")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RepoId", "Partition", "Name")
                        .IsUnique();

                    b.ToTable("ConfigProperty", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LedgerFlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LedgerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MappingReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Partition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecordObject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RouteReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerFlowId");

                    b.HasIndex("RepoId", "FlowName", "Interface", "Partition")
                        .IsUnique();

                    b.ToTable("Interface", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryLease", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("AcquiredUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WorkBatch")
                        .HasColumnType("int");

                    b.HasKey("PartitionId", "Token");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("SubmissionId", "ExpiresUtc");

                    b.HasIndex("PartitionId", "FlowId", "ExpiresUtc");

                    b.ToTable("Lease", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryLedger", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LedgerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PartitionId", "FlowId");

                    b.HasIndex("FlowId")
                        .IsUnique();

                    b.ToTable("Ledger", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryLedgerPartition", b =>
                {
                    b.Property<short>("PartitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("PartitionId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PartitionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LedgerPartition", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Yaml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "TemplateVersion");

                    b.HasIndex("RepoId", "Kind");

                    b.HasIndex("RepoId", "Reference")
                        .IsUnique();

                    b.ToTable("Mapping", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryPartition", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Name");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("Partition", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryRecord", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<long?>("CacheSetId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimedTargetId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("LastDeliveredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("LastSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastVerifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastVerifyOutcome")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MappingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetadataHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("PayloadModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingDocumentRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("PendingMetadata")
                        .HasColumnType("bit");

                    b.Property<string>("PendingMetadataHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("PendingPayload")
                        .HasColumnType("bit");

                    b.Property<string>("PendingPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PendingPayloadLocation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PendingPayloadModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingReferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendingRenderContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendingSourceFileName")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("PendingSourceFingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PendingSourceModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PendingSourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PendingSourceUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingStepJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanRequestedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RenderContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SourceInsertedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SourceKeyJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("SourceModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SourceUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TargetVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WaitingFor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int?>("WorkBatch")
                        .HasColumnType("int");

                    b.HasKey("PartitionId", "FlowId", "DeliveryKey");

                    b.HasIndex("ClaimedTargetId")
                        .IsUnique()
                        .HasFilter("[ClaimedTargetId] IS NOT NULL");

                    b.HasIndex("LeaseOwner");

                    b.HasIndex("LastSubmissionId", "WorkBatch");

                    b.HasIndex("PartitionId", "DeliveryKey");

                    b.HasIndex("PartitionId", "Label");

                    b.HasIndex("PartitionId", "SourceFileName");

                    b.HasIndex("PartitionId", "SourceKey");

                    b.HasIndex("PartitionId", "TargetId");

                    b.HasIndex("PartitionId", "UpdatedUtc");

                    b.HasIndex("PartitionId", "WaitingFor")
                        .HasFilter("[WaitingFor] IS NOT NULL");

                    b.HasIndex("CacheSetId", "DeliveryKey", "FlowId")
                        .HasFilter("[CacheSetId] IS NOT NULL");

                    b.HasIndex("PartitionId", "FlowId", "Label");

                    b.HasIndex("PartitionId", "FlowId", "LastDeliveredUtc");

                    b.HasIndex("PartitionId", "FlowId", "LastVerifiedUtc");

                    b.HasIndex("PartitionId", "FlowId", "LastVerifyOutcome");

                    b.HasIndex("PartitionId", "FlowId", "PlanRequestedUtc")
                        .HasFilter("[PlanRequestedUtc] IS NOT NULL");

                    b.HasIndex("PartitionId", "FlowId", "SourceKey");

                    b.HasIndex("PartitionId", "FlowId", "TargetId");

                    b.HasIndex("PartitionId", "FlowId", "UpdatedUtc");

                    b.HasIndex("PartitionId", "Status", "UpdatedUtc");

                    b.HasIndex("PartitionId", "FlowId", "LastSubmissionId", "UpdatedUtc");

                    b.HasIndex("PartitionId", "FlowId", "SourceFileName", "SourceRowNumber");

                    b.HasIndex("PartitionId", "FlowId", "Status", "NextAttemptUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PartitionId", "FlowId", "Status", "NextAttemptUtc"), new[] { "LastSubmissionId", "UpdatedUtc", "PendingDocumentRef" });

                    b.HasIndex("PartitionId", "FlowId", "Status", "UpdatedUtc");

                    b.HasIndex("PartitionId", "FlowId", "LastSubmissionId", "Status", "NextAttemptUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PartitionId", "FlowId", "LastSubmissionId", "Status", "NextAttemptUtc"), new[] { "UpdatedUtc" });

                    b.ToTable("Record", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryRecordEvent", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimDocumentRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("ClaimMetadata")
                        .HasColumnType("bit");

                    b.Property<string>("ClaimMetadataHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("ClaimPayload")
                        .HasColumnType("bit");

                    b.Property<string>("ClaimPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ClaimPayloadModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimRenderContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimSourceFileName")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("ClaimSourceFingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ClaimSourceModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ClaimSourceRowNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClaimSourceUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClaimSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LeaseToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NothingSent")
                        .HasColumnType("bit");

                    b.Property<string>("PendingStepJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Promote")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StepJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TargetVersion")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionId", "EventId");

                    b.HasIndex("PartitionId", "FlowId", "AtUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PartitionId", "FlowId", "AtUtc"), new[] { "LeaseToken" });

                    b.HasIndex("LeaseToken", "FlowId", "DeliveryKey", "EventId");

                    b.ToTable("RecordEvent", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryRecordIdentity", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("PartitionId", "Token", "FlowId", "DeliveryKey");

                    b.HasIndex("PartitionId", "FlowId", "DeliveryKey");

                    b.HasIndex("PartitionId", "FlowId", "Token");

                    b.ToTable("RecordIdentity", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryRetrieval", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<long>("RetrievalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RetrievalId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Files")
                        .HasColumnType("int");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kinds")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ManifestLocation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Query")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Records")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("WindowField")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("WindowFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WindowTo")
                        .HasColumnType("datetime2");

                    b.HasKey("PartitionId", "RetrievalId");

                    b.HasIndex("RetrievalId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("PartitionId", "FlowId", "StartedUtc");

                    b.HasIndex("PartitionId", "FlowId", "Status", "StartedUtc");

                    b.ToTable("Retrieval", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliverySourceWatermark", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ContextHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedThroughUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PartitionId", "FlowId", "Scope");

                    b.ToTable("SourceWatermark", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliverySubmission", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AwaitingApproval")
                        .HasColumnType("bigint");

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<long>("Blocked")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Delivered")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("Failed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Held")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MappingReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Planned")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RenderContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SkippedStale")
                        .HasColumnType("bigint");

                    b.Property<long>("SkippedUnchanged")
                        .HasColumnType("bigint");

                    b.Property<int>("Slices")
                        .HasColumnType("int");

                    b.Property<string>("SourceConnection")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SourceObject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SourceWindowJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("UnchangedAtPush")
                        .HasColumnType("bigint");

                    b.Property<long>("Untracked")
                        .HasColumnType("bigint");

                    b.Property<long>("Waiting")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("WindowFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WindowToUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("PartitionId", "SubmissionId");

                    b.HasIndex("RunId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("PartitionId", "ReceivedUtc");

                    b.HasIndex("PartitionId", "FlowId", "ReceivedUtc");

                    b.HasIndex("PartitionId", "FlowId", "Status");

                    b.HasIndex("PartitionId", "FlowId", "Kind", "ReceivedUtc");

                    b.ToTable("Submission", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Version")
                        .IsUnique();

                    b.ToTable("Template", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryUpdateTag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagId"));

                    b.Property<long>("AffectedRecords")
                        .HasColumnType("bigint");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Cursor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CursorFlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DecidedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("Processed")
                        .HasColumnType("bigint");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SetIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ToVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TagId");

                    b.HasIndex("Status");

                    b.HasIndex("Scope", "Status");

                    b.HasIndex("Scope", "TypeName", "ItemId", "Path", "Status");

                    b.ToTable("UpdateTag", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.DeliveryWorkBatch", b =>
                {
                    b.Property<short>("PartitionId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Delivered")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Failed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Held")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<long>("Retrying")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Waiting")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionId", "SubmissionId", "Index");

                    b.HasIndex("SubmissionId", "Index")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SubmissionId", "Index"), new[] { "Status" });

                    b.HasIndex("PartitionId", "FlowId", "Status", "CreatedUtc");

                    b.ToTable("WorkBatch", "osdu");
                });

            modelBuilder.Entity("SqlFlow.Delivery.Data.OsduSchemaVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("AppliedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMigration")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MinimumCatalogMigration")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModuleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("SchemaVersion", "osdu", t =>
                        {
                            t.HasCheckConstraint("CK_SchemaVersion_SingleRow", "[Id] = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
