//! Build script: embed the entire `docs/reference` corpus into the binary.
//!
//! It reads `docs/reference/manifest.json` and, for every page it lists,
//! generates an `include_str!` entry so the MCP server ships all 71 pages plus
//! the manifest with no runtime file dependency (mirroring how DeltaForge's MCP
//! embeds its enriched docs). Editing any page or the manifest retriggers the
//! build.

use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    // tools/sqlflow-mcp/../../docs/reference
    let ref_dir = Path::new(&manifest_dir).join("../../docs/reference");
    let manifest_path = ref_dir.join("manifest.json");

    let manifest_text = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", manifest_path.display()));
    let manifest: serde_json::Value =
        serde_json::from_str(&manifest_text).expect("manifest.json is not valid JSON");
    let docs = manifest["docs"].as_array().expect("manifest.docs must be an array");

    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit\n");
    generated.push_str("pub static DOC_BODIES: &[(&str, &str)] = &[\n");
    for d in docs {
        let id = d["id"].as_str().expect("doc.id");
        let rel = d["path"].as_str().expect("doc.path");
        let full = ref_dir.join(rel);
        let full_fwd = full.to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={}", full.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            id, full_fwd
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("docs_bodies.rs"), generated)
        .expect("failed to write docs_bodies.rs");
}
