//! Build script: embed the OSDU Delivery documentation corpus into the binary.
//!
//! The corpus is written in SQLFlow's reference format, and SQLFlow's `docs/reference/build_manifest.py`
//! writes its `manifest.json` from the frontmatter of every page (see `osdu/docs/reference/README.md`). This
//! script reads that manifest and generates an `include_str!` entry for every page it lists, so the server
//! ships the pages and the manifest with no runtime file dependency, as SQLFlow's server ships its own. Editing
//! a page or the manifest retriggers the build.
//!
//! `reference` pages resolve under `osdu/docs/reference/`, and `wiki` pages, the decision records, under
//! `osdu/docs/decisions/`.

use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    // osdu/hosts/osdu-delivery-mcp/../../docs/{reference,decisions}
    let docs_dir = Path::new(&manifest_dir).join("../../docs");
    let reference = docs_dir.join("reference");
    let decisions = docs_dir.join("decisions");
    let manifest_path = reference.join("manifest.json");

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let manifest_text = fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        panic!(
            "failed to read {}: {e}; write it with python sqlflow/docs/reference/build_manifest.py (see osdu/docs/reference/README.md)",
            manifest_path.display()
        )
    });
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text)
        .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", manifest_path.display()));
    let docs = manifest["docs"]
        .as_array()
        .unwrap_or_else(|| panic!("{} has no docs array", manifest_path.display()));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n");
    generated.push_str("pub static DOC_BODIES: &[(&str, &str)] = &[\n");
    for (position, doc) in docs.iter().enumerate() {
        let id = doc["id"]
            .as_str()
            .unwrap_or_else(|| panic!("manifest doc at position {position} has no string id"));
        let rel = doc["path"]
            .as_str()
            .unwrap_or_else(|| panic!("manifest doc '{id}' has no string path"));
        let root = match doc["corpus"].as_str().unwrap_or("reference") {
            "reference" => &reference,
            "wiki" => &decisions,
            other => panic!("manifest doc '{id}' names the corpus '{other}'; expected reference or wiki"),
        };
        let full = root.join(rel);
        assert!(
            full.is_file(),
            "manifest doc '{id}' points at {}, which does not exist; regenerate the manifest",
            full.display()
        );
        println!("cargo:rerun-if-changed={}", full.display());
        let full_fwd = full.to_string_lossy().replace('\\', "/");
        generated.push_str(&format!("    ({id:?}, include_str!({full_fwd:?})),\n"));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("delivery_doc_bodies.rs"), generated)
        .expect("failed to write delivery_doc_bodies.rs");
}
