# Rebuilds .sqlflow\env for local dev, reading the live values straight from Azure.
#
#   powershell -ExecutionPolicy Bypass -File scripts\dev-setup.ps1
#
# Run this once, and again whenever a connection string or key rotates in the estate. It needs
# 'az login' with access to the resource group.
#
# WHY IT READS CONTAINER APP SECRETS, NOT KEY VAULT: the Key Vault copies of these connection
# strings (dw-sqlflow-prod, dw-pre-prod, dw-dwh-prod) were stale in BOTH host and password. They
# named dw-sql-mi-prod, a managed instance that NO LONGER EXISTS; the estate runs on dw-mi-sql-prod.
# Using them gets a connection that fails with a misleading "transient failure ... consider
# EnableRetryOnFailure" error. The container apps' own secrets are what the running system uses, so
# they are the only trustworthy source.
$ErrorActionPreference = "Stop"

$rg = "datawarehouse-west-rg-prod-v2"
$app = "sqlflow-v3-control-plane"
$worker = "sqlflow-v3-worker"
# The SPA app registration backing the GUI's Microsoft sign-in button, looked up by display name.
$entraAppName = "SQLFlow V3 GUI"
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot ".sqlflow\env"

Write-Host "Reading live configuration from Azure ..."
az account show 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Error "Not logged in to Azure. Run: az login" }

function Get-AppSecret([string]$name) {
    $v = az containerapp secret show -n $app -g $rg --secret-name $name --query value -o tsv 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($v)) { Write-Error "Could not read container app secret '$name'." }
    return $v
}
function Get-WorkerSecret([string]$name) {
    $v = az containerapp secret show -n $worker -g $rg --secret-name $name --query value -o tsv 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($v)) { Write-Error "Could not read worker secret '$name'." }
    return $v
}

$catalog = Get-AppSecret "catalog-db"
$jwt     = Get-AppSecret "jwt-signing-key"
$git     = Get-AppSecret "git-token"
# From the WORKER app: it is the thing that actually runs flows against pre/ods.
$pre     = Get-WorkerSecret "pre-conn"
$dwh     = Get-WorkerSecret "dwh-conn"

# Issuer/audience must match the estate's, or a token minted by the cloud GUI is rejected locally.
$issuer   = az containerapp show -n $app -g $rg --query "properties.template.containers[0].env[?name=='ControlPlane__Jwt__Issuer'].value | [0]" -o tsv
$audience = az containerapp show -n $app -g $rg --query "properties.template.containers[0].env[?name=='ControlPlane__Jwt__Audience'].value | [0]" -o tsv

# Entra SSO for the GUI's "Sign in with Microsoft" button. Discovered, not hardcoded: the tenant is whichever one
# 'az login' is on, and the SPA app registration is found by name. SSO is additive, so a tenant without that
# registration is not an error: the button simply stays hidden and username/password still works.
$entraTenant = az account show --query tenantId -o tsv
$entraClient = az ad app list --filter "displayName eq '$entraAppName'" --query "[0].appId" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($entraClient)) {
    $entraBlock = @"
# --- Entra SSO: OFF ---
# No '$entraAppName' app registration was found in tenant $entraTenant, so the GUI offers username/password only.
# Create a single-tenant SPA registration of that name with http://localhost:5173 as a redirect URI to turn it on.
"@
} else {
    $entraBlock = @"
# --- Entra SSO: the GUI's "Sign in with Microsoft" button ---
# Turns itself on because both ids are present; there is no separate Enabled flag to set. The registration is a
# SPA whose redirect URI is http://localhost:5173, matching the origin MSAL asks for (window.location.origin), so
# the GUI must be on exactly that port for the popup to come back.
#
# FIRST Entra sign-in PROVISIONS THE USER just-in-time, with DefaultRole (viewer), IN THE SHARED CATALOG: it is a
# real row in the real estate, not a local one. Raise the role from the GUI's user admin afterwards if needed.
ControlPlane__AzureAd__TenantId=$entraTenant
ControlPlane__AzureAd__ClientId=$entraClient
"@
}

New-Item -ItemType Directory -Force -Path (Split-Path $envPath) | Out-Null

$content = @"
# SQLFlow local dev. NEVER COMMITTED: .sqlflow/ is git-ignored (.gitignore:49).
# GENERATED by scripts\dev-setup.ps1 from the live estate. Re-run it after any secret rotation.
#
# Everything RUNS on this machine; every resource is the REAL Azure estate: the same catalog, the
# same pre/ods databases, the same lake. You are debugging the live system, locally.
#
# EVERY value comes from CONTAINER APP SECRETS, never Key Vault: the Key Vault copies were stale in
# both host and password, naming the retired dw-sql-mi-prod instance.

# --- Catalog: the real Azure catalog, byte-identical to what the container app uses ---
SQLFLOW_CATALOG_DB=$catalog
ControlPlane__Catalog__ConnectionReference=$catalog

# The catalog EXISTS and is SHARED, so never let a local run provision one.
ControlPlane__Bootstrap__AllowCreate=false

# Do NOT migrate the shared catalog from a laptop by default. Local code is usually ahead of what is
# deployed, and applying an unfinished migration here breaks the running container apps: they are on
# older code and would hit columns they do not know about.
# Flip to true ONLY when deliberately testing a migration, accepting that it hits the estate.
ControlPlane__Bootstrap__ApplyMigrations=false

# No admin bootstrap: the shared catalog already has your users, so your normal GUI login works.
# Setting AdminUsername/AdminPasswordReference would try to re-provision the admin in the SHARED
# catalog and could rewrite the estate's admin password.

# --- One process: API + scheduler + worker, so the whole system runs under one debugger ---
ControlPlane__Worker__Enabled=true

# Vite's origin. The allowlist defaults to EMPTY, and empty means no CORS at all, so without this
# every GUI call fails with a CORS error.
ControlPlane__Cors__AllowedOrigins__0=http://localhost:5173

# Same signing key/issuer/audience as the estate, so tokens are interchangeable.
ControlPlane__Jwt__SigningKey=$jwt
ControlPlane__Jwt__Issuer=$issuer
ControlPlane__Jwt__Audience=$audience

$entraBlock

# --- Cloud auth: Key Vault and the data lake go through your 'az login' ---
# This is what makes `${keyvault:...} refs in flow YAML resolve locally with no extra config.
SQLFLOW_AZURE_AUTH=cli

# --- The real pre and ods databases, exactly as the flows reference them ---
SQLFLOW_CONN_DWPREPROD=$pre
SQLFLOW_CONN_DWDWHPROD=$dwh

# --- Repo sync ---
SQLFLOW_GIT_USERNAME=x-bitbucket-api-token-auth
SQLFLOW_GIT_TOKEN=$git
"@

Set-Content -Path $envPath -Value $content -Encoding utf8
Write-Host "Wrote $envPath"
Write-Host ""
Write-Host "  Catalog:  $(($catalog -split ';' | Where-Object { $_ -match '^(Server|Database)=' }) -join '; ')"
Write-Host ""
Write-Host "Next:  dev.bat        (or F5 in VS Code -> 'SQLFlow: Dev (F5)')"
